wallpaper {
    monitor = DP-2
    #monitor = HDMI-A-3
    path = ~/Pictures/wallpapers/MyBeloved.jpg
    fit_mode = cover
}
wallpaper {
    monitor = HDMI-A-1
    #monitor = DP-5
    path = ~/Pictures/wallpapers/MyBeloved.jpg
    fit_mode = cover
}
wallpaper {
    monitor = DP-3
    #monitor = DP-4
    path = ~/Pictures/wallpapers/MyBeloved.jpg
    fit_mode = cover
}
